// <auto-generated />
namespace WebRaoTin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_benefit_attributes_on_VLTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_benefit_attributes_on_VLTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109271806375_add_benefit_attributes_on_VLTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
