// <auto-generated />
namespace WebRaoTin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adddate_join : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddate_join));
        
        string IMigrationMetadata.Id
        {
            get { return "202111202053170_add date_join"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
