// <auto-generated />
namespace WebRaoTin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AllowNull_Salary_PriceBDS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowNull_Salary_PriceBDS));
        
        string IMigrationMetadata.Id
        {
            get { return "202109271747260_AllowNull_Salary_PriceBDS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
