// <auto-generated />
namespace WebRaoTin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Config_BinhLuan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Config_BinhLuan));
        
        string IMigrationMetadata.Id
        {
            get { return "202110301839585_Config_BinhLuan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
